---
- hosts: localhost
  become: true
  tasks:
#  - name: Add archlinuxfr repository
#    copy:
#      src: files/etc/pacman.conf
#      dest: /etc/pacman.conf
#      owner: root
#      group: root
#      mode: 644
  - name: Update the package cache
    package:
      update_cache: yes
  - name: Install necessary utilities
    package:
      name: "{{ item }}"
    with_items:
      - openssh
      - vim
      - screen
      - powerline-fonts
      - zsh-theme-powerlevel9k
      - papirus-icon-theme
      - base-devel
  - name: Install programming tools
    package:
      name: "{{ item }}"
    with_items:
#      - nodejs
#      - npm
#      - yarn
      - jdk8-openjdk
      - jdk10-openjdk
      - maven
  - name: Install DevOps utilities
    package:
      name: "{{ item }}"
    with_items:
      - virtualbox-host-modules-arch
      - virtualbox
      - vagrant
      - docker
  - name: Add user to docker group
    user:
      name: "{{ ansible_user_id }}"
      append: yes
      groups: docker
- hosts: localhost
  tasks:
  - name: Copy user preferences
    copy:
      src: "files/HOME/{{ item }}"
      dest: "{{ ansible_user_dir }}/{{ item }}"
    with_items:
      - .screenrc
      - .zshrc
- hosts: localhost
  become: true
  tasks:
  - name: GUI Setup
    package:
      name: "{{ item }}"
    with_items:
      - gnome
      - networkmanager
      - gnome-tweak-tool
      - libreoffice-fresh
      - evolution
      - evolution-ews
      - firefox
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - bluez
      - bluez-libs
      - bluez-utils
      - tilda
  - name: Install Development Tools
    package:
      name: "{{ item }}"
    with_items:
      - git
      - eclipse-java
#      - atom
  - name: Enable GUI Services
    service:
      name: "{{ item }}"
      enabled: yes
    with_items:
      - gdm
      - bluetooth
      - NetworkManager
